Repository cloud-native-toolkit/image-cli-tools-azure, pull requests merged in 2022-08, with the labels that each got.

#8 Updated base image to v1.3.1
  Dockerfile-alpine
  Dockerfile-fedora
Labels: bug, minor

#9 Updates base image to v1.4.0
  .github/workflows/docker-build.yaml
  Containerfile
  Containerfile-alpine
  Containerfile-fedora
  Dockerfile
Labels: feature, minor

#10 Updates base to v1.4.1
  Containerfile-alpine
  Containerfile-fedora
Labels: bug, patch

#11 Updates base image (cli-tools-core) to v1.4.2
  .github/workflows/docker-build.yaml
  .github/workflows/update-base-image.yaml
  Containerfile-alpine
  Containerfile-fedora
Labels: chore, patch

#12 Updates cloud-native-toolkit/image-cli-tools-core module to v1.4.3
  Containerfile-alpine
  Containerfile-fedora
Labels: bug, patch

#13 Updates cloud-native-toolkit/image-cli-tools-core module to v1.4.4
  Containerfile-alpine
  Containerfile-fedora
Labels: bug, patch

#14 Updates cloud-native-toolkit/image-cli-tools-core module to v1.4.5
  Containerfile-alpine
  Containerfile-fedora
Labels: bug, patch

#15 Updates cloud-native-toolkit/image-cli-tools-core module to v1.4.6
  Containerfile-alpine
  Containerfile-fedora
Labels: bug, patch
